# Code from class

In [1]:
import numpy as np

In [2]:
np.array([[1.], [0.]])

array([[1.],
       [0.]])

In [3]:
np.block([[1.], [0.]])

array([[1.],
       [0.]])

In [4]:
np.array([[0.], [0.]])

array([[0.],
       [0.]])

In [5]:
np.block([[1.], [np.array([[0.], [0.]])]])

array([[1.],
       [0.],
       [0.]])

In [6]:
np.block([[1.], [np.zeros([2, 1])]])

array([[1.],
       [0.],
       [0.]])

In [7]:
n = 10
np.block([[1.], [np.zeros([n - 1, 1])]])

array([[1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [8]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [9]:
import sympy as sym

In [10]:
s = sym.symbols('s')

In [11]:
A = sym.Matrix([[-3, -5], [1, 0]])

In [12]:
A.charpoly(s)

PurePoly(s**2 + 3*s + 5, s, domain='ZZ')

In [13]:
k1, k2 = sym.symbols('k1, k2')

In [14]:
K = sym.Matrix([[k1, k2]])
B = sym.Matrix([[1], [0]])

In [15]:
K

Matrix([[k1, k2]])

In [16]:
B

Matrix([
[1],
[0]])

In [17]:
B * K

Matrix([
[k1, k2],
[ 0,  0]])

In [18]:
A - B * K

Matrix([
[-k1 - 3, -k2 - 5],
[      1,       0]])

In [19]:
(A - B * K).charpoly(s)

PurePoly(s**2 + (k1 + 3)*s + k2 + 5, s, domain='ZZ[k1,k2]')

# A few extra notes after class

We know that the characteristic polynomial of $A$ is defined as

$$\det\left(sI - A\right).$$

So, we could have computed this characteristic polynomial without using `charpoly` as follows:

In [20]:
sym.det(s * sym.eye(2) - A).collect(s)

s**2 + 3*s + 5

In hindsight, this is what I should have done — less magic! Similarly, here is the characteristic polynomial of $A - BK$:

In [21]:
sym.det(s * sym.eye(2) - (A - B * K)).collect(s)

k2 + s**2 + s*(k1 + 3) + 5